CREATE database 

---------------------

CREATE TABLE TypeAdherent (
    idTypeAdherent INT GENERATED BY DEFAULT AS IDENTITY,
    qualificatif VARCHAR(255),
    dureePenalite INT, -- nombre de jours
);

CREATE TABLE Adherent(
    idAdherent INT GENERATED BY DEFAULT AS IDENTITY,
    idTypeAdherent int REFERENCES TypeAdherent (idTypeAdherent),
    idTypeAbonnement int REFERENCES TypeAbonnement (idTypeAbonnement),
    nom VARCHAR(255),
    prenom VARCHAR(255),
    dateAdhesion datetime
);

CREATE TABLE Abonnement(
    idAbonnement INT GENERATED BY DEFAULT AS IDENTITY,
    dateDebut date,
    dateFin date 
);

CREATE TABLE TypeLecture (
    idTypeLecture INT GENERATED BY DEFAULT AS IDENTITY,
    libelle VARCHAR(255)
);

CREATE TABLE LectureAdherent (
    idLectureAdherent INT GENERATED BY DEFAULT AS IDENTITY,
    idTypeAdherent INTEGER REFERENCES TypeAdherent (idTypeAdherent),
    idTypeLecture INTEGER REFERENCES TypeLecture (idTypeLecture),
    nbLivresMax int,
    dureeMaxParLivre NUMERIC(10,2) -- duree : /heure ? /jour?
);

CREATE TABLE Exemplaire (
    idExemplaire INT GENERATED BY DEFAULT AS IDENTITY,
    idLivre INTEGER REFERENCES Livre(idLivre),
    nbExemplaire int
);

CREATE TABLE Penalite (
    idPenalite INT GENERATED BY DEFAULT AS IDENTITY,
    idAdherent int ,
    datePenalite datetime
);

CREATE TABLE Status (
    idStatus INT GENERATED BY DEFAULT AS IDENTITY,
    VARCHAR(255)
);

CREATE TABLE StatusPret (
    idPret INT GENERATED BY DEFAULT AS IDENTITY,
    idAdherent int ,
    idExemplaire int,
    idStatus INTEGER REFERENCES Tag (idTag)
); 

CREATE TABLE Pret (
    idPret INT GENERATED BY DEFAULT AS IDENTITY,
    idAdherent int ,
    idExemplaire int ,
    datePret datetime 
);

------------------------------------------------------



CREATE TABLE Livre (
    idLivre INT GENERATED BY DEFAULT AS IDENTITY,
    titre VARCHAR(255),
    isbn VARCHAR(20), -- Changement ici
    auteur VARCHAR(255),
    editionLivre VARCHAR(255),
    PRIMARY KEY(idLivre)
);


CREATE TABLE Tag (
    idTag INT GENERATED BY DEFAULT AS IDENTITY,
    nomTag VARCHAR(255),
    Primary key(idTag)
);

CREATE TABLE TagLivre (
    idTagLivre INT GENERATED BY DEFAULT AS IDENTITY,
    idLivre INTEGER REFERENCES Livre (idLivre),
    idTag INTEGER REFERENCES Tag (idTag)
);

-- Remplissage de la table Livre
INSERT INTO Livre (titre, isbn, auteur, editionLivre) VALUES
('Le Petit Prince', '9782070612758', 'Antoine de Saint-Exupéry', 'Gallimard'),
('1984', '9780451524935', 'George Orwell', 'Secker & Warburg'),
('L Etranger', '9782070360024', 'Albert Camus', 'Gallimard'),
('Harry Potter a l ecole des sorciers', '9782070643028', 'J.K. Rowling', 'Gallimard Jeunesse'),
('Le Seigneur des Anneaux', '9782266122224', 'J.R.R. Tolkien', 'Pocket');

-- Remplissage de la table Tag
INSERT INTO Tag (nomTag) VALUES
('Classique'),
('Science-Fiction'),
('Jeunesse'),
('Philosophie'),
('Fantastique');

-- Associations dans TagLivre (livres et tags associés)
INSERT INTO TagLivre (idLivre, idTag) VALUES
(1, 1), -- Le Petit Prince - Classique
(1, 3), -- Le Petit Prince - Jeunesse
(2, 1), -- 1984 - Classique
(2, 2), -- 1984 - Science-Fiction
(3, 1), -- L'Étranger - Classique
(3, 4), -- L'Étranger - Philosophie
(4, 3), -- Harry Potter - Jeunesse
(4, 5), -- Harry Potter - Fantastique
(5, 5); -- Seigneur des Anneaux - Fantastique