\c postgres;
DROP DATABASE IF EXISTS spring_1_film;
CREATE DATABASE spring_1_film;
\c spring_1_film;

CREATE TABLE Film (
    idFilm INT GENERATED BY DEFAULT AS IDENTITY,
    titre VARCHAR(255),
    dateSortie DATE,
    PRIMARY KEY (idFilm)
);

CREATE TABLE Categorie (
    idCategorie INT GENERATED BY DEFAULT AS IDENTITY,
    nomCategorie VARCHAR(255),
    PRIMARY KEY(idCategorie)
);

CREATE TABLE CategorieFilm (
    idCategorieFilm INT GENERATED BY DEFAULT AS IDENTITY,
    idFilm INTEGER REFERENCES Film (idFilm),
    idCategorie INTEGER REFERENCES Categorie (idCategorie)
);

INSERT INTO Categorie (nomCategorie) VALUES
('Drame'),
('Comedie'),
('Romance'),
('Action'),
('Science fiction'),
('Adulte');